# Generated by Django 5.1 on 2025-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='591ab9c4aec8cbaec7489b9112c420af83f1f3edf8fa098bd0e16ef807adc9f9', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_power', models.CharField(max_length=100)),
                ('max_torque', models.CharField(max_length=100)),
                ('cooling_system', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('displacement', models.IntegerField()),
                ('cylinders', models.IntegerField()),
                ('gear_shifting_pattern', models.CharField(max_length=100)),
                ('fuel_tank_capacity', models.FloatField()),
                ('mileage_owner_reported', models.FloatField()),
                ('top_speed', models.IntegerField()),
                ('braking_system', models.CharField(max_length=100)),
                ('front_brake_type', models.CharField(max_length=100)),
                ('tyre_type', models.CharField(max_length=100)),
                ('rear_brake_type', models.CharField(max_length=100)),
                ('wheel_type', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('display_system', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('suspension', models.CharField(max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
            ],
        ),
    ]
