# Generated by Django 5.1 on 2025-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='3759ec09d99d3ce8e893e5f4f215d77c4315bf2d466d99b26280cfedf6fff171', max_length=64, unique=True),
        ),
    ]
