# Generated by Django 5.1 on 2025-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='f0b11507a717a3bbf3fc638aa5e64bc6864bb7b641b757ef2356b6a87fe2c8e5', max_length=64, unique=True),
        ),
    ]
