# Generated by Django 5.1 on 2025-04-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='9032f5e602a17ca3595e0a8372a07c95c1f179c69ca1821c9dcbdb19f527450a', max_length=64, unique=True),
        ),
    ]
