# Generated by Django 5.2.1 on 2025-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0004_alter_apikey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default="76973b84e045da804b69eedc0f9366b2a1146f11f7322b1a90885fb8d1cb23f9",
                max_length=64,
                unique=True,
            ),
        ),
    ]
